### ISSUE TITLE
Checkout don't work

### ISSUE THREAD

**Issue by sergiotranchino** [nexopos/v3-issues#13]
Hello, checkout don't work when i click on merge order after i have selected a order che button checkout don't work!
Thank you

**Comment by Blair2004** [comment]
Hi, thank you for your review. Note that in order to understand what you're facing, we would like you to post that issue following the Bug Submittion template available : https://github.com/nexopos/v3-issues/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

So please consider create an issue well explained using that template.
