### ISSUE TITLE
Barcode scanner on add item page

### ISSUE THREAD

**Issue by getmehire** [nexopos/v3-issues#141]
**Username**:  GetMeHire 

**Is your feature request related to a problem? Please describe.**
According to your support team barcode scanner is working on pos page but not add item page. Adding a barcode manually is such a big pain. I hope customers like me who has thousands of products can understand the frustration. Therefore this is a much needed feature.

**Describe the solution you'd like**
Barcode scanner and populating barcode automatically with real product barcode

**Describe alternatives you've considered**
No alternatives.

**Additional context (optional)**
Null

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "getmehire" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by nexopos** [comment]
Hi, we've not been able to find the username "GetMeHire" on [Nexo Platform](https://api.nexopos.com).
                    You might consider updating your issue and mention your username. 
                    Regards.

**Comment by Blair2004** [comment]
A product can be created in 2 differents ways on NexoPOS : 
1 - Create the product manually
2 - Import the product
While creating a product might be tedious for thousand products, importing seems to be an easier solution. 

Using a barcode is only required for the stock taking. This let you retreive the product saved on the db and you can proceed by filling up the quantities. The barcode doesn't share any information about the item ( nor name, quantities and so on). It's then not necessary to implement that feature while creating items. However, if you would like to use the barcode value of an item while creating that item on NexoPOS, you can use a barcode to fill the barcode field.

Closing the issue since it's not pratical.

**Comment by getmehire** [comment]
But still can you do this. It's a lot of time consuming, doing it manually or with CSV file. You already have the function. Just make the barcode field populate automatically when product is scanned using a hardware. Just like you said it is working on checkout.
