### ISSUE TITLE
SHOP MANAGER can see all stores on list even i setup he cant have access to all stores

### ISSUE THREAD

**Issue by lrp2019** [nexopos/v3-issues#236]
**Username** : 
LEORP

**Describe the bug**
If i create an user on MANAGE USERS left menu item (outside store) AND on ACCESS MANAGER left menu item (outside store) i setup this user to have access to store 1 and not to store 2 when i login with this user, this user can see both stores on stores list.

If i try access the store 2, show a page with message: YOU DONT HAVE ACCESS TO THIS STORE. This is ok BUT the correct is the manager of store 1 dont see the store 2 on list, it is not professional thing.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: latest version updated on nexopos update page on 29 july 2019
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by nexopos** [comment]
<p>Hi, here is a quick recap of your licences on <a href="https://api.nexopos.com">Nexo Platform</a>.</p>
                            <table>
                                <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Application</td>
                                        <td>Support Expire</td>
                                        <td>Used</td>
                                        <td>Status</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                <td>16195010</td>
                                <td>NexoPOS - Extendable PHP Point of Sale</td>
                                <td>2019-11-06 22:11:05</td>
                                <td>Used</td>
                                <td>Supported</td>
                            </tr>
                                </tbody>
                            </table>

**Comment by Blair2004** [comment]
You should usually consider providing informations about your system (module installed).

**Comment by Blair2004** [comment]
What we noticed is that most of the time, the Store Manager has access to the store management, which includes: create, edit, delete stores. With that access allowed, even with a store restriction, he can still see the store (since he can create, see, edit and delete them). The solution is then to make sure that the Store Manager can't do such actions.

Furthermore, we noticed that when after removing these permissions, the top button with the "Home" icon which usually takes to the store's list, was taking to an Access Denied page, when the store manager didn't have access to the management of the stores. That's why on the next update of NexoPOS, we've made that link to change according to the shop manager permissions to see or not the store list (permission: nexo.view.stores).

**Comment by lrp2019** [comment]
The problem WAS NOT SOOLVED.

The problem continues on page http://sitename/dashboard/nexo/stores where the user MANAGER can see all stores on this page even he doesnt have permission.

It is true the user cant enter in the stores he doesnt have permission but as i told before, it is not proffessional let one user see other stores that he doesnt have permission.

**Comment by Blair2004** [comment]
Have you updated the system to the last version ?

**Comment by lrp2019** [comment]
Yes friend.
I undertand well how update system works ;) I updated and checked because i only can use nexopos after fix this problem.

**Comment by lrp2019** [comment]
THIS WAS NOT AN ISSUE, SORRY.

THANKS FOR ATTENTION
