### ISSUE TITLE
No way to change size of the text and fields in receipt

### ISSUE THREAD

**Issue by araufqazi** [nexopos/v3-issues#240]
**arauf.qazi@gmail.com** : 
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
Im having issues with the formatting of the receipt.
First of all, the text size cant be changed.
Secondly, the items in the columns cannot be put in a different line. i.e. order number and date are printed together in one line so it creates confusion.
Thirdly, there are too many fields under the subtotal and these fields take up half the receipt. There should be a way to choose which fields we want to show. i.e. I just want subtotal, tax, discount, total, paid. That's it.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**

**Comment by Blair2004** [comment]
Hi, we do seriously take all the issues into consideration. In order to help us process your issue more faster, the more details you provide, the easier it is for us to understand and resolve. Meantime, we do not know if you're using NPS receipt conversion into image or not. 

If you have a suggestion like hiding some fields from the receipt, you should consider posting that as a separate suggestion. 

Your images are also welcome. A screenshot could help us to understand better the situation (along with the details you provided).

**Comment by araufqazi** [comment]
Hi,
Yes I'm using NPS as an image.
I think what I have mentioned is quite straight forward. In the "invoice &
receipts" sections, you have set 2 columns. In those columns we can add
fields that we want to show.
However, those fields cannot be displayed in separate lines.
Also there is an issue of the font size. There is no way to set that.
And finally, there is an issue with the order total fields.

**Comment by nexopos** [comment]
Hi, i think it has been partially convered herer : https://nexopos.com/nexopos-3-14-49-nexo-print-server-2-5-0-the-changelog-explained/

**Comment by Blair2004** [comment]
What is the status of this so far ?
