### ISSUE TITLE
Error in the product price editing

### ISSUE THREAD

**Issue by israelga** [nexopos/v3-issues#25]
Because when you modify the unit price of a product, does VAT not change with respect to the price? The same error happens when you make a discount on a product.

Watch the video https://www.screencast.com/t/rWXmmJam

**Comment by Blair2004** [comment]
We've not been able to reproduce the issue. Have you edited the script manually ?
![record3](https://user-images.githubusercontent.com/5265663/42963254-97c0ec1e-8b8b-11e8-870c-fcfcef0e2923.gif)

**Comment by israelga** [comment]
No, I have not edited anything.

**Comment by Blair2004** [comment]
That's why it's important to submit issue following the table offered. so that we can know which version you're using.
Here is an example of how issue should be posted : https://github.com/nexopos/v3-issues/issues/26

Consider sharing your environment details, as requested on the template : https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md
