### ISSUE TITLE
Múltiple enhancements 

### ISSUE THREAD

**Issue by manuelpeh** [nexopos/v3-issues#3]
Hello I have been trying the pos for a while I have several features that could enhance the functionality of the script 
lets get started 
A.- multiple prices of an item that could be based on two aspects 
1.- the first aspect could be based on an amount basis 
2.- the second basis can be based on client type or client price list asigned 
For example:
product A: price 1, 2, 3, 4
Let the admin assign how much pieces are for each price or set in the client profile which price it will have or if the client have a certain type of user (value customer, high value customer, retailer,etc.. each type or role can be asigned to a price)
 
B.- client type 
For example 
 (value customer, high value customer, retailer,etc.. each type or role can be asigned to a price)

C.- back orders 
Let the cashier sell products on back order, in that the inventory is not updated until you change the status from back order to a complete sale status, that is when you update inventory, with this you avoid inventory issues of errors. In this case when you make a sale and before doing it if the product was on stock and after doing the sale is not that producto should be in back order so the inventory doesn’t go to negative 

D.- RMA
This modules make total enhancements for the pod because when you have a client who ask you for warranty you do an rma it discount again a piece from inventory but doesn’t affect payments and let you keep tracking of bad products so you can ask your supplier for warranty  too

**Comment by Blair2004** [comment]
Thank you, your suggestion will be reviewed.

**Comment by nexopos** [comment]
A - This is the variations and the unit of measure. We had that on mind yet. Still trying to figure out how to implement it. Good idea anyway.

B - This case is a complex price assignation based on customer/retailer role. We had something that we called Shadow Price, the shadow price is a price which can be adjusted on the POS, but which can't exceed the treshold. But it has been removed since no one where using it. This might be complicated to implement that feature as explained.

C - Selling items even if the stock is exhausted ? Why not. we should consider how this should affect the report or the stock flow as well.

D - Are you talking about returning goods ? there is a such feature on the system, but it just refund the custom and keep a track of the damaged product.

Thank you for your contribution. Your idea is approuved.

**Comment by manuelpeh** [comment]
I can give you more complex information I’m a developer too so I can give you some pseudo code

**Comment by manuelpeh** [comment]
For the back order sale as I told you is considering that when you make the sale of the product is on back order you should not decrease stock ( to avoid issues) and just update the cash flow 
Give that sale a back order status and change it manually when you are going to end the sale 
Create a new table to handle all back orders (paid and waiting, on process, shipped and finished)

**Comment by Blair2004** [comment]
What happen if when you try to proceed to complete the order, some item has their stock exhausted and other not ?

**Comment by manuelpeh** [comment]
If you make the order for a product in backorder it let you do but doesnt
modify stock and put the status in under process

The stock is modified when you select process order in the status

**Comment by nexopos** [comment]
The idea has been stored https://github.com/nexopos/v3-issues/projects/2
