### ISSUE TITLE
Issues : NexoPOS issues found on receipt and on payments

### ISSUE THREAD

**Issue by scilang** [nexopos/v3-issues#33]
### RECEIPT PROBLEM
When we take an order and then sending to the kitchen, in print page, It doesn't appears customer name or the shortcode we added. These just appears when we receive payment. this reason, the waiters are having trouble figuring out which table the order will go.

![1](https://user-images.githubusercontent.com/35400199/42995409-77fff88c-8c19-11e8-9bb7-e5c4e22a6dd7.PNG)
![2](https://user-images.githubusercontent.com/35400199/42995411-78304d70-8c19-11e8-89bd-6acc52b2634c.PNG)

### THE TAXES
The taxes must be inclusive with products. You are thinking that you have already done it. But When we do this, Products are being shown without tax price in pos dashboard. I mean Price 39.5 $ must be shown totally into  inclusive tax 39.5$ 
in the following section should be informed that there is such tax in this product. if you check all pos systems you will see that Every pos system is working like this.

### ORDER PAYMENTS
we want to get a payment, we take half or part of this payment in cash, the other part we take it with the credit card, until here, That's great. But if we go to reports and check in detailed reports part, you will see that all the payment is received in cash.
I think that It is a bug. If you check you will see.

There are lot s of things I have seen so far. I wrote the priority ones I believe that these problems will be solved quickly

THANK YOU, GOOD LUCK  AND BEST REGARDS

**Comment by Blair2004** [comment]
Hi, i would like to remind you first, that there is a template to follow when you submit an issue. That template ask some question which might provide us useful information to treat the request. However, regarding the receipt issue, here is what has been done from our end.

![record3](https://user-images.githubusercontent.com/5265663/43033820-03cc5d92-8cc9-11e8-9ae7-662eaa9fd70a.gif)

As you can see, the template is updated, even when the order is send to the kitchen, that makes me ask you to provide your environment details. Here is the template which needs to be follow in order to help us treating your query.

**Username**
Provide a username as created on Nexo Platform: https://api.nexopos.com/register. Only the owner of the account can POST an issue.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - NexoPOS: [e.g. 3.12.12]
 - Gastro (if installed) [e.g. 2.3.10]
 - PHP version [e.g. 7.1]
 - MySQL version [5.6]
 - Devise used (desktop browser, smartphone, POS system).

**Additional context**
Add any other context about the problem here.

**Comment by scilang** [comment]
Unfortunately, this result is insufficient for me.. if I open a new table, The waiters must know the orders going to which tables in the restaurant. 

Table numbers must write on the print page. 

THANKS BEST REGARDS..

**Comment by Blair2004** [comment]
Let me try with the table and area template.

**Comment by scilang** [comment]
Ok I will be waiting for your respond..

**Comment by scilang** [comment]
Thank you Mr. Blair You made a great work. There is one more thing related to VAT...

The taxes must be inclusive with products. I mean Price 39.5 $ must be shown totally into inclusive tax 39.5$. we just should show  how much tax there is in the product we added in pos dashboard.

I will be checking your system until end of this month. if you ensure that the entire system runs smoothly, your project can be the best seller in envato just like the plugin I mentioned about to you.
I think that you are making terrible effort in this system but you are on the right track.. and also I want to thank you for Mr Vishal..  just like Everytime I said, He is very good at his job. and he is very helpful.
![ekran alintisi](https://user-images.githubusercontent.com/35400199/43200262-a66498c4-901d-11e8-8b08-8ac8bdf71a38.PNG)

**Comment by nexopos** [comment]
Regarding the product. Have what is the tax type ? inclusive or exclusive ?

**Comment by Blair2004** [comment]
A good guide on how the tax works on NexoPOS is needed. Since there is a misunderstanding here. Anyway, closed due to inactivity.
