### ISSUE TITLE
Daily Sales & Detail Report different?

### ISSUE THREAD

**Issue by sandisurya** [nexopos/v3-issues#55]
**Username**
sandisurya

**Describe the bug**
Daily Sales & Detail report are different in SUM

**Screenshots**
![whatsapp image 2018-08-18 at 8 22 09 am](https://user-images.githubusercontent.com/41579628/44318790-73b82b80-a462-11e8-8d08-3161843919ff.jpeg)

Register Daily Report
![whatsapp image 2018-08-18 at 8 23 39 am](https://user-images.githubusercontent.com/41579628/44318808-8599ce80-a462-11e8-9db5-d6414fb44aa8.jpeg)
![whatsapp image 2018-08-18 at 8 23 02 am](https://user-images.githubusercontent.com/41579628/44318809-86326500-a462-11e8-85e0-c8376670c202.jpeg)

**Environment (please complete the following information):**
 - NexoPOS: 3.13.1
 - Gastro (if installed): 2.3.18
 - PHP version: 7.1.7
 - MySQL version: 5.6
 - Devise used desktop: browser

**Additional context**
I will email the DB if you need to check

**Comment by Blair2004** [comment]
Hi, 
after having reviewed on DB and the script, we've found that there as an issue with the translation and not with the calculation. Let me explain that in details:

## First Sale Analysis
The first sale analysis is normally the real value of orders. You can assume it to be the TOTAL value of an order.  So regarding that value on the report, it's okay.

## Second Sale Analysis
The second on is rather the total value of the payment type. Let me make it more simple. If you have an order which total is 950 USD for example, paid with 1 cash payment (1000 USD), it's the payment value which is considered here. So 1000 and not 950 USD. This part of the report count then all payment values mades and sum it. That's why it's often greater than the first value (first sale analysis value).
