### ISSUE TITLE
Detailed Sales Report Issue

### ISSUE THREAD

**Issue by vishalwalia1** [nexopos/v3-issues#86]
Detailed Sales Report Not Showing Multiple Payment when sale made - 
like after done with payment with Multiple  mode , Cash Payment and  Credit Card 
only show multiple payment done , please see the screenshot 

![index1](https://user-images.githubusercontent.com/32275898/45869857-269fe000-bda7-11e8-9614-22f7ef22d5ce.jpg)

**Comment by nexopos** [comment]
Hi, It looks like your issue does'nt actually match the required format.
                Please note that you can choose between the following format : 
                    - [Issue](https://github.com/nexopos/v3-issues/issues/new?template=bug_report.md).
                    - [Feature Submition](https://github.com/nexopos/v3-issues/issues/new?template=feature_request.md).
                You might consider updating your issue and use the right version format. 
                Regards.

**Comment by Blair2004** [comment]
What is the version used here ?
NexoPOS ? 
Php version ? 
That's the reason why we have have a template.

**Comment by vishalwalia1** [comment]
Php 7.1

![capture1](https://user-images.githubusercontent.com/32275898/45874048-8307fd00-bdb1-11e8-89d7-d6612d2f115f.PNG)

**Comment by Blair2004** [comment]
Ok, thank you

**Comment by Blair2004** [comment]
Hi, After having reviewed the issue here is our answer.
Actually it's not a bug. As long as more that one payment type is involved, they are added under the label "Multiple Payment". 

##Why ? 

Actually, the exact amount of the payment type is not relevant for the detailed report. Let's assume we have a payment of 100 USD for an order which total is 90 USD. Is that relevant to display 100 USD instead of 90USD ? 

##About Splitted Payment Type Amount
if we have an order with 2 payments for example Cash : 50 USD, Credit Card : 50 USD, for an order of 90 USD. The detailed report cannot list Cash 50 USD, and Credit Card 50 USD, the result is not true and unrelevant since wait is actually on the register is 90 USD. So, we've then used the exact amount of an order instead of using the total of the payment made.
